name: stamp
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - charset-normalizer=3.1.0
  - cudatoolkit=11.8.0
  - idna=3.4
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - numexpr=2.8.4
  - openssl=3.0.8
  - packaging=23.1
  - pandas=1.5.3
  - pip=23.1.2
  - platformdirs=3.5.3
  - pooch=1.7.0
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - certifi==2023.5.7
      - dill==0.3.6
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.20.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.54.2
      - h5py==3.8.0
      - jax==0.4.12
      - keras==2.12.0
      - libclang==16.0.0
      - markdown==3.4.3
      - markupsafe==2.1.3
      - ml-dtypes==0.2.0
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cudnn-cu11==8.6.0.163
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - protobuf==4.23.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.10.1
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.1
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-io-gcs-filesystem==0.32.0
      - termcolor==2.3.0
      - tqdm==4.65.0
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.14.1