#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=train_stamp_rs
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:15:00
#SBATCH --mem=32000M
#SBATCH --output=job_logs/training_slurm_%A.out

module purge

source activate rs_env

# For 64 version:
# srun python3 cmain.py -m stamp_rsc -d rsc15_64 -n -e 1

# For 4 version:
srun python3 cmain.py -m stamp_rsc -d rsc15_64 -n -e 1